# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zip_content_comparator}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Szymon (jeznet) Je\305\274"]
  s.date = %q{2010-08-17}
  s.description = %q{An utility for comparing content of ZIP files.
It does not extract the files anywhere, its's using instead ZIP::ZipFile class
from rubyzip gem which enables to access ZIP files like a file system.
It uses MD5 to compare files.
}
  s.email = %q{szymon@jez.net.pl}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/zip_content_comparator.rb",
     "nbproject/project.properties",
     "nbproject/project.xml",
     "test/data/zip_content_comparator/identical_to_reference_test_file.zip",
     "test/data/zip_content_comparator/modified_class_file.zip",
     "test/data/zip_content_comparator/one_file_added.zip",
     "test/data/zip_content_comparator/one_file_added_deleted_and_changed.zip",
     "test/data/zip_content_comparator/one_file_changed.zip",
     "test/data/zip_content_comparator/one_file_deleted.zip",
     "test/data/zip_content_comparator/reference_test_file.zip",
     "test/test_suite.rb",
     "test/test_zip_content_comparator.rb",
     "zip_content_comparator.gemspec"
  ]
  s.homepage = %q{http://github.com/jeznet/zip_content_comparator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An utility for comparing content of ZIP files.}
  s.test_files = [
    "test/test_suite.rb",
     "test/test_zip_content_comparator.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.1"])
    else
      s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<rubyzip>, [">= 0.9.1"])
  end
end

